// -*- mode: c++ -*-
// 
// File /home/gibelin/Programs/Geant4/samurai/simtree_length.C generated by TMultiDimFit::MakeRealCode
// on Thu Jul  6 21:24:48 2017
// ROOT version 5.32/00
//
// This file contains the function 
//
//    double  MDF(double *x); 
//
// For evaluating the parameterization obtained
// from TMultiDimFit and the point x
// 
// See TMultiDimFit class documentation for more information 
// 
//
// Static data variables
//
static int    gNVariables    = 6;
static int    gNCoefficients = 60;
static double gDMean         = 9478.35;
// Assignment to mean vector.
static double gXMean[] = {
  -0.0649118, 0.113415, 0.0182191, 0.0192747, 0.286251, 0.292524 };

// Assignment to minimum vector.
static double gXMin[] = {
  -86.0487, -98.4333, -0.0434778, -0.0514167, -1141.92, -177.43 };

// Assignment to maximum vector.
static double gXMax[] = {
  86.5223, 81.4119, 0.0436185, 0.0514507, 902.787, 97.4918 };

// Assignment to coefficients vector.
static double gCoefficient[] = {
  2212.54,
  1128.11,
  66.6048,
  -12562.8,
  -175.163,
  3171.04,
  43995,
  0.603801,
  3.50536,
  851.307,
  12262.6,
  538.23,
  2390.77,
  -18.1708,
  -16.0787,
  9.34527,
  -1762.84,
  4189.18,
  -0.0829336,
  11.1331,
  -8167.68,
  3.0382,
  -1.3527,
  0.440975,
  0.659518,
  -5908.5,
  34257.4,
  -1.5336,
  -4.42253,
  -0.0943999,
  -1.47054,
  20234.6,
  -117423,
  1.30974,
  1.33784,
  3.34193,
  0.00986761,
  4.40468,
  -18.7337,
  0.220116,
  -0.453857,
  -25.2412,
  -36.5527,
  1.67437,
  106.305,
  0.388215,
  8.72502,
  -0.173847,
  -0.374524,
  -3.63737,
  0.11693,
  0.275178,
  -0.170991,
  -0.012932,
  0.0115382,
  0.0396083,
  -0.0618439,
  0.00808604,
  -0.0873438,
  0.0926644
 };

// Assignment to error coefficients vector.
static double gCoefficientRMS[] = {
  1664.14,
  1774.76,
  83.9619,
  12376.7,
  1654.57,
  1961.73,
  42371.8,
  6.35955,
  26.7916,
  5658.28,
  9114.36,
  146.109,
  1389.88,
  8.07391,
  8.69727,
  9.07974,
  467.011,
  3102.99,
  23.7476,
  42.4205,
  4758.87,
  8.08105,
  52.1312,
  3.26724,
  6.4666,
  3274.56,
  27411.7,
  58.029,
  181.436,
  9.23476,
  13.2982,
  11213.4,
  93952.8,
  21.8521,
  90.0781,
  27.0275,
  53.4571,
  176.355,
  30.6015,
  17.9146,
  37.7641,
  35.8527,
  37.0075,
  43.4039,
  85.1124,
  3.63399,
  84.8224,
  37.8103,
  9.60448,
  163.439,
  15.0475,
  30.2619,
  11.448,
  3.88027,
  37.2698,
  13.5849,
  34.3824,
  45.7973,
  41.8158,
  151.481
 };

// Assignment to powers vector.
// The powers are stored row-wise, that is
//  p_ij = gPower[i * NVariables + j];
static int    gPower[] = {
  1,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  1,  2,
  2,  1,  1,  1,  1,  1,
  1,  1,  1,  1,  2,  1,
  1,  1,  2,  1,  1,  1,
  1,  1,  1,  1,  1,  3,
  1,  1,  1,  1,  2,  2,
  1,  3,  1,  1,  1,  1,
  2,  1,  2,  1,  1,  1,
  1,  1,  2,  1,  1,  2,
  1,  2,  1,  1,  1,  2,
  1,  1,  1,  1,  3,  1,
  1,  2,  1,  2,  1,  1,
  1,  1,  2,  1,  2,  1,
  2,  1,  1,  1,  2,  1,
  1,  1,  1,  3,  1,  1,
  1,  1,  1,  1,  3,  2,
  1,  2,  1,  1,  1,  3,
  1,  2,  1,  3,  1,  1,
  1,  2,  1,  2,  2,  1,
  1,  2,  1,  2,  1,  2,
  1,  1,  3,  1,  1,  1,
  2,  1,  1,  3,  1,  1,
  2,  1,  1,  1,  3,  1,
  3,  1,  1,  1,  1,  1,
  2,  1,  1,  2,  1,  1,
  1,  2,  1,  1,  2,  1,
  1,  1,  2,  3,  1,  1,
  1,  2,  2,  2,  1,  1,
  3,  1,  1,  1,  2,  1,
  1,  1,  1,  3,  2,  1,
  2,  1,  1,  2,  1,  2,
  1,  2,  1,  1,  2,  2,
  1,  1,  1,  2,  2,  2,
  1,  1,  1,  2,  1,  1,
  1,  2,  2,  1,  1,  1,
  1,  1,  3,  2,  1,  1,
  2,  1,  2,  2,  1,  1,
  2,  2,  1,  1,  2,  1,
  1,  3,  1,  2,  1,  1,
  2,  1,  2,  1,  2,  1,
  1,  2,  2,  1,  2,  1,
  2,  1,  1,  2,  2,  1,
  3,  1,  1,  2,  1,  1,
  1,  2,  1,  1,  3,  1,
  1,  1,  2,  1,  3,  1,
  2,  2,  1,  1,  1,  2,
  2,  3,  1,  1,  1,  1,
  1,  3,  1,  1,  2,  1,
  2,  2,  1,  2,  1,  1,
  2,  1,  3,  1,  1,  1,
  1,  1,  2,  2,  1,  1,
  1,  1,  3,  1,  2,  1,
  1,  1,  1,  2,  3,  1,
  3,  2,  1,  1,  1,  1,
  3,  1,  2,  1,  1,  1,
  1,  1,  2,  2,  2,  1,
  1,  2,  3,  1,  1,  1,
  1,  3,  2,  1,  1,  1,
  2,  2,  2,  1,  1,  1
};

// 
// The function   double MDF(double *x)
// 
double MDF(double *x) {
  double returnValue = gDMean;
  int    i = 0, j = 0, k = 0;
  for (i = 0; i < gNCoefficients ; i++) {
    // Evaluate the ith term in the expansion
    double term = gCoefficient[i];
    for (j = 0; j < gNVariables; j++) {
      // Evaluate the polynomial in the jth variable.
      int power = gPower[gNVariables * i + j]; 
      double p1 = 1, p2 = 0, p3 = 0, r = 0;
      double v =  1 + 2. / (gXMax[j] - gXMin[j]) * (x[j] - gXMax[j]);
      // what is the power to use!
      switch(power) {
      case 1: r = 1; break; 
      case 2: r = v; break; 
      default: 
        p2 = v; 
        for (k = 3; k <= power; k++) { 
          p3 = p2 * v;
          p3 = 2 * v * p2 - p1; 
          p1 = p2; p2 = p3; 
        }
        r = p3;
      }
      // multiply this term by the poly in the jth var
      term *= r; 
    }
    // Add this term to the final result
    returnValue += term;
  }
  return returnValue;
}

// EOF for /home/gibelin/Programs/Geant4/samurai/simtree_length.C
